project_id = "zjemlaextbkmctjbeukr"

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.verify-google-purchase]
verify_jwt = false

[functions.verify-apple-receipt]
verify_jwt = false

[functions.verify-face]
verify_jwt = false
